### ISSUE TITLE
cannot start due to pypdf weirdness: AttributeError: 'module' object has no attribute 'generic'

### ISSUE THREAD

**Issue by muelli** [tuxor1337/springerdownload#19]
cannot start:

```
>python3 ./springer_download.py 
Traceback (most recent call last):
  File "./springer_download.py", line 6, in <module>
    from springerdl import meta, util, download, merge
  File "/home/muelli/vcs/springerdownload/springerdl/merge.py", line 9, in <module>
    from .pyPdf_ext import PdfFileReader_ext as PdfFileReader
  File "/home/muelli/vcs/springerdownload/springerdl/pyPdf_ext.py", line 29, in <module>
    pyPdf.generic.createStringObject = _new_createStringObject
AttributeError: 'module' object has no attribute 'generic'
```

**Comment by tuxor1337** [comment]
You either have to install the python module pyPdf so that it's in your path (e.g. under fedora that means "yum install pyPdf") or you manually replace the directory `./springerdl/PyPDF2` by the corresponding directory from the source code at https://github.com/mstamy2/PyPDF2. The dependence on pyPdf is included in the README. (Hence, the second option is actually inofficial and for testing purposes only.)

**Comment by muelli** [comment]
I used pip to install PyPDF2.

```
➜ springerdownload git:(master) ✗>
/var/tmp/pypdf/bin/python -c "import PyPDF2; print(PyPDF2.__path__)"
['/var/tmp/pypdf/local/lib/python2.7/site-packages/PyPDF2']
➜ springerdownload git:(master) ✗>
```

That in itself doesn't help as this bug report suggest.

Because shipping a well packaged library is weird I tried to remove the directory, but then this program is unhappy: 
```
Traceback (most recent call last):
  File "springer_download.py", line 6, in <module>
    from springerdl import meta, util, download, merge
  File "/home/muelli/vcs/springerdownload/springerdl/merge.py", line 9, in <module>
    from .pyPdf_ext import PdfFileReader_ext as PdfFileReader
  File "/home/muelli/vcs/springerdownload/springerdl/pyPdf_ext.py", line 6, in <module>
    from . import PyPDF2 as pyPdf
ImportError: cannot import name PyPDF2
```

Unfortunately, the setup.py is not based on setuptools so it makes life harder when it comes to defining dependencies.

**Comment by tuxor1337** [comment]
Yes, that's because PyPDF2 is not the same as pyPdf. As I said, the original and official dependence is on pyPdf. Only for testing purposes I included an option to use PyPDF2 instead by putting the code into the `./springerdl/PyPDF2` directory.

**Comment by muelli** [comment]
ah. right. `/var/tmp/pypdf/bin/pip install cssselect pyPdf` seems to make it work.
It'd be cool if `setup.py install` or `pip install . ` also worked.
Bonus points if that pulls the necessary dependencies.

**Comment by tuxor1337** [comment]
For some reason, I decided to not include the dependencies into the setup script. Must have been similar to the reason why I chose `distutils` over `setuputils`. Maybe that's related to the `single_file` option that I wanted to add. If you can rewrite `setup.py` accordingly feel free to do so.
