### ISSUE TITLE
indexError: list index out of range

### ISSUE THREAD

**Issue by bamsarts** [tuxor1337/springerdownload#20]
==> Fetching book info...Traceback (most recent call last):
  File "springer_download.py", line 155, in <module>
    sys.exit(main())
  File "springer_download.py", line 19, in main
    interface(springer_fetch)
  File "/home/bamsarts/script/springerdownload/springerdl/interface/cli.py", line 85, in __init__
    fetcher(self)
  File "springer_download.py", line 37, in springer_fetch
    info = meta.fetchBookInfo(root)
  File "/home/bamsarts/script/springerdownload/springerdl/meta.py", line 23, in fetchBookInfo
    chapter_cnt = root.cssselect("span.chapter-count")[0].text_content()
IndexError: list index out of ran

**Comment by bamsarts** [comment]
any idea ?

**Comment by tuxor1337** [comment]
Hey, unfortunately Springer changes the page layout from time to time so that I have to adapt a lot of stuff to keep the html parser working. I quickly changed some lines, which fixed the above error for me (see latest commit).
